# Site settings
title: TAILHQ
tag_text: TAIL
description: "Highly modular and scalable platforms for inference, learning and decision making."
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
